# Generated by Django 3.1.5 on 2021-01-24 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardapp', '0004_auto_20210123_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
